# Generated by Django 3.2.3 on 2021-06-29 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='slug')),
                ('code', models.CharField(choices=[('l', 'Code Lespérance')], default='l', max_length=1, verbose_name='code')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.meeting', verbose_name='meeting')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('managers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='managers')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', verbose_name='organisation'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='sequence number')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('start_at', models.DateTimeField(blank=True, help_text='When set, the point should not start after this time.', null=True, verbose_name='start at')),
                ('reached_at', models.DateTimeField(blank=True, null=True, verbose_name='reached at')),
                ('current', models.BooleanField(default=False, verbose_name='current')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.point', verbose_name='parent point')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.session', verbose_name='session')),
            ],
            options={
                'verbose_name': 'point',
                'verbose_name_plural': 'points',
                'unique_together': {('session', 'parent', 'seq')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('organisation', 'slug')},
        ),
    ]
