# Generated by Django 3.2.10 on 2022-01-13 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organisations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='slug')),
                ('code', models.CharField(choices=[('l', 'Code Lespérance')], default='l', max_length=1, verbose_name='code')),
                ('access', models.CharField(choices=[('p', 'public'), ('P', 'participant'), ('M', 'manager'), ('m', 'member')], default='M', max_length=1, verbose_name='access rule')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('M', 'manager'), ('m', 'member')], max_length=1)),
            ],
            options={
                'verbose_name': 'membership',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='sequence number')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('start_at', models.DateTimeField(blank=True, help_text='When set, the point should not start after this time.', null=True, verbose_name='start at')),
                ('reached_at', models.DateTimeField(blank=True, null=True, verbose_name='reached at')),
                ('current', models.BooleanField(default=False, verbose_name='current')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.point', verbose_name='parent point')),
            ],
            options={
                'verbose_name': 'point',
                'verbose_name_plural': 'points',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.meeting', verbose_name='meeting')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='PointFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=organisations.models.get_file_path, verbose_name='file')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.point', verbose_name='point')),
            ],
            options={
                'verbose_name': 'point file',
                'verbose_name_plural': 'point files',
            },
        ),
        migrations.AddField(
            model_name='point',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.session', verbose_name='session'),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('logo', models.FileField(blank=True, null=True, upload_to=organisations.models.get_logo_path, verbose_name='logo')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('members', models.ManyToManyField(through='organisations.Membership', to=settings.AUTH_USER_MODEL, verbose_name='members')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='MembershipInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('role', models.CharField(default=None, max_length=1, verbose_name='role')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'membership invitation',
                'verbose_name_plural': 'membership invitations',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', verbose_name='organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('session', 'parent', 'seq')},
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('organisation', 'slug')},
        ),
    ]
