# Generated by Django 3.2.10 on 2022-01-13 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('role', models.CharField(choices=[('p', 'president'), ('s', 'secretary'), ('m', 'member'), ('o', 'observer')], default='m', max_length=1, verbose_name='role')),
                ('voting', models.IntegerField(default=0, verbose_name='voting power')),
                ('speaking', models.BooleanField(default=False, verbose_name='speaking')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.meeting', verbose_name='meeting')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
            },
        ),
        migrations.CreateModel(
            name='ParticipantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('role', models.CharField(default=None, max_length=1, verbose_name='role')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.meeting', verbose_name='meeting')),
            ],
            options={
                'verbose_name': 'participant invitation',
                'verbose_name_plural': 'participant invitations',
                'unique_together': {('email', 'meeting')},
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, choices=[('R', 'Ordinary'), ('P', 'Privileged'), ('O', 'Order'), ('I', 'Information')], default='R', max_length=1, verbose_name='priority')),
                ('time_asked', models.DateTimeField(blank=True, null=True, verbose_name='time asked')),
                ('time_granted', models.DateTimeField(blank=True, null=True, verbose_name='time granted')),
                ('seq', models.PositiveIntegerField(blank=True, null=True, verbose_name='sequence number')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('motion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motions.motion', verbose_name='motion')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speakers.participant', verbose_name='participant')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.point', verbose_name='point')),
            ],
            options={
                'verbose_name': 'intervention',
                'verbose_name_plural': 'interventions',
                'unique_together': {('point', 'motion', 'seq')},
            },
        ),
    ]
