# Generated by Django 3.2.3 on 2021-06-29 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motions', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('role', models.CharField(choices=[('p', 'president'), ('s', 'secretary'), ('m', 'member')], default='m', max_length=1, verbose_name='role')),
                ('voting', models.BooleanField(default=False, verbose_name='voting')),
                ('speaking', models.BooleanField(default=False, verbose_name='speaking')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.meeting', verbose_name='meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_asked', models.DateTimeField(verbose_name='time asked')),
                ('time_granted', models.DateTimeField(verbose_name='time granted')),
                ('seq', models.PositiveIntegerField(verbose_name='sequence number')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('motion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motions.motion', verbose_name='motion')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speakers.participant', verbose_name='participant')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.point', verbose_name='point')),
            ],
            options={
                'verbose_name': 'intervention',
                'verbose_name_plural': 'interventions',
                'unique_together': {('point', 'motion', 'seq')},
            },
        ),
    ]
